### PR TITLE
Closes #1313

### LINKED ISSUE #1313: flow-typed v2.2.0 fails on windows
```
npx flow-typed
...\node_modules\flow-typed\dist\cli.js
Invalid regular expression: /definitions\npm\(@[^\]*\)?[^\]*\?/: Unterminated character class
```

It doesn't matter what commands I run and what folder I run them in - end result is the same.

* node v8.1.2
* Windows 10 x64

### PR DESCRIPTION
**Pull request by jkomyno**
From NodeJS' docs:

> path.sep provides the platform-specific path segment separator:
> - \ on Windows
> - / on POSIX

> Note: On Windows, both the forward slash (/) and backward slash (\) are accepted as path segment separators; however, the path methods only add backward slashes (\).

Backward slashes resulted in breaking flow-typed for Windows. This PR fixes it.

### CODE REVIEW

**Comment by GAntoine** [comment]
Thanks for the PR! Do you think this would also fix #1234 ?

File: cli/src/commands/runTests.js [hunk 1]
```diff
@@ -47,7 +47,7 @@ type TestGroup = {
  * directory.
  */
 const basePathRegex = new RegExp(
-  `definitions${path.sep}npm${path.sep}(\@[^${path.sep}]*${path.sep})?[^${path.sep}]*${path.sep}?`,
+  'definitions/npm/(\@[^/]*/)?[^/]*/?',
```
Comment (GAntoine) [inline cli/src/commands/runTests.js]: Place everything on one line to make the specs pass:
```
const basePathRegex = new RegExp(REGEX);
```

Comment (jkomyno) [reply cli/src/commands/runTests.js]: Yeah I just noted, it was a PR on the fly so I didn't clone the project and tested the lint by myself.
Edit incoming

**Comment by jkomyno** [comment]
@GAntoine it should be fine now

**Comment by GAntoine** [comment]
@kulmajaba Since you were gonna open a PR, would you mind taking a look at this? I'm happy with it, but let me know if you see any glaring issues.

**Comment by kulmajaba** [comment]
Looks good to me, I've nothing to add.

**Comment by GAntoine** [comment]
Then it's accepted, thanks again for your help.

File: cli/src/commands/runTests.js [hunk 2]
```diff
@@ -46,9 +46,7 @@ type TestGroup = {
  * structs. Each TestGroup represents a Package/PackageVersion/FlowVersion
  * directory.
  */
-const basePathRegex = new RegExp(
-  `definitions${path.sep}npm${path.sep}(\@[^${path.sep}]*${path.sep})?[^${path.sep}]*${path.sep}?`,
-);
+const basePathRegex = new RegExp('definitions/npm/(@[^/]*/)?[^/]*/?');
```
Comment (HyperBrain) [inline cli/src/commands/runTests.js]: @GAntoine Does this still work with `\` as path separator? I think the checks for `^/` will miss a backslash on Windows as well as the terminating optional `/`.
The correct fix should be to use `path.sep`, but to double it in case it is a backslash (correct Regex escape).

E.g.
```
...\flow-typed\definitions\npm\mylib\
```
would not match

Comment (GAntoine) [reply cli/src/commands/runTests.js]: It no longer works with a backslash, but according to

> Note: On Windows, both the forward slash (/) and backward slash (\\) are accepted as path segment separators;

that shouldn't be an issue.

Comment (HyperBrain) [reply cli/src/commands/runTests.js]: Yes, Windows works with forward slashes for all fs operations, but my point was, that the regex is used to _parse_ incoming paths, which still have backslashes embedded on Windows, so the forward slash only regex is unsuitable to parse Windows paths.

Comment (GAntoine) [reply cli/src/commands/runTests.js]: Oh I see, I wasn't aware of that... Would you mind opening a new issue? I'll ping the right people and we can discuss it there. I don't work on windows so I can't really verify either change, more deeply then how sound they look.
